### ISSUE TITLE
turn example into single action

### ISSUE THREAD

**Issue by kalantar** [IBM/actions-ibmcloud#4]
I am confused by why this is called an action. This seems to be a sample workflow that shows what steps are needed to do a login/cluster config. Why not replace all of it with an action that hides this from the user. Use would be a single step; something like:

```yaml
    - uses: kalantar/iks@main
      with:
        IBM_CLOUD_API_KEY: ${{ secrets.IBM_CLOUD_API_KEY }}
        IBM_CLOUD_RESOURCE_GROUP: <fill in>
        IBM_CLOUD_REGION: <fill in>
        IKS_CLUSTER: <fill in>
```

As an example, I created https://github.com/kalantar/iks. However, I am not very familiar with the login process and do not know if there are other cases/inputs that should be handled by such an action. Or if there are suitable defaults.
